### ISSUE TITLE
Perceptual Reader: up/down arrow scrolls page, even when focused on sketch

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#130]
Similarly, mouse-movements outside the canvas also affect the sketch itself (in the instructions, for example)

I think that, ideally, key-presses automatically affect the sketch (and not the page), with or without focus, while mouse-movements only affect the sketch if over the canvas or the canvas has focus

But I'm not really sure what correct behavior is here...

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/133
I was able to prevent default key events for all arrow keys, but still can't get keyDown events passed to iframe.

**Comment by dhowe** [comment]
Ok. Though mouse is still active outside of the canvas, in the instructions for example --is it possible to give focus to the canvas, but not the entire iframe?

**Comment by cqx931** [comment]
This is more related to the p5 js page rather than the iframe.
In p5.js the entire browser window triggers mouse events.
Please check the fix here: https://github.com/dhowe/Website/pull/134

Reference:
https://github.com/dhowe/Website/pull/133/commits/6fd8442a990211296b9a7440079a2935f2952bdc
https://github.com/processing/p5.js/issues/752

**Comment by cqx931** [comment]
Can this be closed?
