### ISSUE TITLE
New website organization to support indexable pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#140]
Would like, for example,  each project to come up in search results as 'The XYZ project, by Daniel Howe', etc...

**Comment by cqx931** [comment]
If I try to search a project that doesn't have it's own website, what comes up is the homepage
![image](https://user-images.githubusercontent.com/3056154/31106003-23ff7174-a7b6-11e7-9364-13a49b8aaac6.png)

I don't know how exactly I can do this for the detail pages, because all the project detail pages are now in one html. If I add all the project-specific meta tags in header, how could the search engine relate them with the correct links(Ex: detail.html#advertisingpositions)?

TODO:
more meta tags to [AdverPos](http://www.rednoise.org/daniel/adverpos/)

**Comment by dhowe** [comment]
can the meta tags need to be generated dynamically in javascript, based on the url?

**Comment by cqx931** [comment]
I'm not sure whether this can be solved only by dynamic meta tags. 
In my understanding, the urls for detailed project pages such as http://rednoise.org/daniel/detail.html#chinaeye won't be crawled by the bots, which is why the search result will end up in the index page with its short project description.

**Comment by dhowe** [comment]
yes, I was thinking about (they already exist for some of the projects) ... but still needs to have the meta-tags in the html

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/Website/pull/236. 
Not sure how this is going to show up in the search result, but here is the dynamic meta tag.

**Comment by cqx931** [comment]
This should be helpful: https://websiteseochecker.com/blog/hashbang-seo-in-2019-a-complete-guide-to-hash-bang-urls/

**Comment by cqx931** [comment]
https://twitter.com/JohnMu/status/1118844020816584707?ref_src=twcamp%5Ecopy%7Ctwsrc%5Eandroid%7Ctwgr%5Ecopy%7Ctwcon%5E7090%7Ctwterm%5E3

**Comment by dhowe** [comment]
I think we want a rewrite rule that looks something like:
```
RewriteEngine on
RewriteRule detail/([A-Za-z0-9_]+)/$ detail.html#$1
```

**Comment by dhowe** [comment]
this just needs testing: see https://rednoise.org/newdch

**Comment by dhowe** [comment]
done
