### ISSUE TITLE
NEXT buttons not working8216

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#171]
at least on firefox (url changes, but page does not reload)

To recreate:
Go to first page (spectre), then click 'next' on lower right

![Screen Shot 2019-06-16 at 1 35 46 PM](https://user-images.githubusercontent.com/737638/59563532-6690ac80-9033-11e9-80ec-9cc545e8e6df.png)

**Comment by dhowe** [comment]
temp fix in bc145ae, please check **

**Comment by cqx931** [comment]
One question regarding to "NEXT button":
What happens to those projects without detailed information? For example, dialogic links to the github page directly when clicked from the home page. However, one can still see a page on the project accessed through "NEXT button". 

Currently there is a bug for projects without long descriptions.  I can fix this, but it still looks quite weird especially for cases like dialogic. Shall I remove these projects from LAST/NEXT buttons? Another way to solve this is to add more info for these projects so that they won't look too different from the rest.

Currently there are two projects lack of detailed information in project.json file:
All your Google are Belong to Us
Dialogic

**Comment by dhowe** [comment]
I guess they should be skipped for now...

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/Website/commit/9be54b2b9326e0ee13f8b03aa720a8bbb49e243b
