### ISSUE TITLE
Vertical scroll for page content (index/detail pages)

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#33]
So footer is always visible... 
Is this a bad idea?

**Comment by cqx931** [comment]
I have moved to the current solution for screen size like 13inch mac. Since the screen size is quite limited there, the space left for the content would be very small and influence the user experience.

Or a better solution could be to have a fixed footer for screen height larger than 1000px, while on smaller screen the footer still stays at the bottom of the page.

**Comment by dhowe** [comment]
agreed -- is this a lot of work?

**Comment by cqx931** [comment]
I have implemented it here, please check whether it cause other troubles that are hard to notice.
https://github.com/dhowe/Website/pull/35/commits/639e09cefcbaebf9338f740bcea92b13f4fdebaf

**Comment by dhowe** [comment]
nice
